import type { LookEntry } from '@/types/look'

export const seedLooks: LookEntry[] = [
  {
    lookId: 'look-001-arid-geometry',
    lookSlug: 'arid-geometry',
    lookTitle: 'Arid Geometry',
    season: 'AW',
    year: 2026,
    heroImageUrl: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=1400&q=90&auto=format&fit=crop',
    heroImageAlt: 'Model in structured charcoal coat against a sunlit ochre wall in Karen, Nairobi',
    priceKES: 48000,
    availableUnits: 3,
    status: 'published',
    publishedAt: '2026-03-01T08:00:00Z',
    editorialStory: {
      lookTitle: 'Arid Geometry',
      season: 'AW',
      year: 2026,
      pullQuote: 'There is a precision in dryness — a discipline that only the Kenyan highland understands.',
      narrativeBody:
        'The coat begins as an argument against softness. Charcoal wool woven tight enough to hold its own silhouette, structured at the shoulder with a geometry borrowed from the Ngong Hills at dusk — flat planes, hard shadows, no apology.\n\nIt is not a coat for comfort. It is a coat for arrival. The collar stands independent of the neck, the sleeves taper not to the wrist but to a deliberate stop three centimetres above it. Every decision is a refusal.\n\nWorn here against the ochre plaster of a Karen compound wall, the garment becomes architectural — a third wall in the frame. The model does not wear the coat; she occupies it.',
      moodKeywords: ['arid', 'geometric', 'highland', 'structured', 'refusal'],
      credits: {
        photographer: 'Amara Osei',
        tailor: 'Wanjiku Mwangi',
        stylist: 'Kefilwe Nkosi',
        model: 'Aisha Kimani',
        location: 'Karen, Nairobi',
      },
    },
    tailorSpec: {
      lookId: 'look-001-arid-geometry',
      fabricComposition: [
        {
          layerName: 'Shell',
          materialName: 'Kenyan Highland Wool',
          composition: '100% Virgin Wool',
          weightGSM: 380,
          sourceRegion: 'Molo, Nakuru County',
        },
        {
          layerName: 'Interlining',
          materialName: 'Woven Hair Canvas',
          composition: '70% Wool, 30% Goat Hair',
          weightGSM: 240,
          sourceRegion: 'Imported — Italy',
        },
        {
          layerName: 'Lining',
          materialName: 'Bemberg Cupro',
          composition: '100% Cupro',
          weightGSM: 95,
          sourceRegion: 'Imported — Japan',
        },
      ],
      stitchingMethod: 'Hand-padstitched canvas construction. Lapels hand-basted to canvas for three days before final press. Pick stitching at pocket edges — 8 stitches per centimetre.',
      constructionNotes: 'Single-breasted, 3-button. Welted chest pocket. Two jetted hip pockets with concealed flap. Back vent — single, 32cm. Buttons: hand-turned buffalo horn from Laikipia.',
      measurements: {
        chest: 96,
        waist: 84,
        hip: 98,
        shoulderWidth: 42,
        sleeveLength: 60,
      },
      tailorNotes: 'Press the collar stand with a damp cloth at 180°C — never steam directly onto the wool face. The shoulder seam must sit exactly 1cm behind the natural shoulder point. No exceptions.',
      estimatedHours: 62,
      difficultyRating: 5,
    },
  },
  {
    lookId: 'look-002-red-laterite',
    lookSlug: 'red-laterite',
    lookTitle: 'Red Laterite',
    season: 'SS',
    year: 2026,
    heroImageUrl: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=1400&q=90&auto=format&fit=crop',
    heroImageAlt: 'Wide-leg cotton trousers and structured top against red Kenyan earth',
    priceKES: 32000,
    availableUnits: 5,
    status: 'published',
    publishedAt: '2026-03-10T08:00:00Z',
    editorialStory: {
      lookTitle: 'Red Laterite',
      season: 'SS',
      year: 2026,
      pullQuote: 'The earth here is the colour of ambition — iron-rich, loud, unashamed.',
      narrativeBody:
        'Laterite soil is the colour that European painters spent centuries trying to name. Burnt sienna gets close. Venetian red misses the warmth. The Kenyan earth simply is what it is — uninterested in translation.\n\nThe trousers carry that refusal into fabric. Woven from raw cotton grown in Machakos, dyed with iron oxide extracted from the same soil they reference, they are self-contained. No foreign hand in the colour.\n\nThe structured top — collarless, with a single horizontal dart below the bust — is an interruption. White against the red. A deliberate break in the monologue.',
      moodKeywords: ['earth', 'iron', 'warmth', 'monologue', 'Machakos'],
      credits: {
        photographer: 'Seun Adeyemi',
        tailor: 'Grace Otieno',
        location: 'Machakos County',
      },
    },
    tailorSpec: {
      lookId: 'look-002-red-laterite',
      fabricComposition: [
        {
          layerName: 'Shell (Trouser)',
          materialName: 'Machakos Raw Cotton',
          composition: '100% Cotton',
          weightGSM: 220,
          sourceRegion: 'Machakos County, Kenya',
        },
        {
          layerName: 'Shell (Top)',
          materialName: 'Laundered Poplin',
          composition: '100% Cotton',
          weightGSM: 130,
          sourceRegion: 'Thika, Kenya',
        },
      ],
      stitchingMethod: 'Flat-felled seams throughout. French seams at the trouser inseam. Machine-stitched with hand-finished hems.',
      constructionNotes: 'Wide-leg trousers — 28cm hem circumference. High rise, 31cm. Waistband interfaced with fusible. Top: collarless, single horizontal dart below bust, invisible zip at left side seam.',
      measurements: {
        waist: 72,
        hip: 94,
        inseam: 78,
      },
      tailorNotes: 'The iron-oxide dye will fade with repeated washing. Pre-wash the fabric 3 times before cutting to stabilise the colour. Do not use chlorine bleach under any circumstance.',
      estimatedHours: 28,
      difficultyRating: 3,
    },
  },
  {
    lookId: 'look-003-void-column',
    lookSlug: 'void-column',
    lookTitle: 'Void Column',
    season: 'Resort',
    year: 2026,
    heroImageUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=1400&q=90&auto=format&fit=crop',
    heroImageAlt: 'Floor-length black column dress against white minimalist architecture',
    priceKES: 55000,
    availableUnits: 2,
    status: 'published',
    publishedAt: '2026-03-18T08:00:00Z',
    editorialStory: {
      lookTitle: 'Void Column',
      season: 'Resort',
      year: 2026,
      pullQuote: 'Black is not the absence of colour — it is the presence of everything, compressed.',
      narrativeBody:
        'There is a particular silence that a column dress demands from the room it enters. Not the silence of absence — the silence of density. Everything compressed into one vertical plane, sealed at the hem, resolute at the shoulder.\n\nThis one is constructed from double-faced crepe. Two faces, neither dominant. The outer face has a matte finish that absorbs light — not reflects, not rejects: absorbs. The inner face is satin, for the body alone.\n\nThe silhouette has no waist. This is intentional. The waist is where dresses make concessions. This dress does not concede.',
      moodKeywords: ['compression', 'vertical', 'matte', 'resolve', 'night'],
      credits: {
        photographer: 'Amara Osei',
        tailor: 'Wanjiku Mwangi',
        model: 'Zara Muthoni',
        location: 'Nairobi City',
      },
    },
    tailorSpec: {
      lookId: 'look-003-void-column',
      fabricComposition: [
        {
          layerName: 'Shell',
          materialName: 'Double-Faced Wool Crepe',
          composition: '90% Wool, 10% Polyamide',
          weightGSM: 290,
          sourceRegion: 'Imported — France',
        },
      ],
      stitchingMethod: 'Invisible zip at centre back, 55cm. All seams pressed open over a seam roll — no seam allowances visible through the double-face. Hand-slip stitched hem.',
      constructionNotes: 'Floor-length column, 148cm from shoulder seam. No waist seam. Sculpted neckline — shallow square, 9cm × 22cm. Kick pleat at centre back hem, 22cm.',
      measurements: {
        chest: 88,
        hip: 92,
        shoulderWidth: 38,
      },
      tailorNotes: 'Double-faced crepe must be handled as one layer — never separate the faces during construction. Steam press at 160°C with a press cloth. The matte face is the right side.',
      estimatedHours: 44,
      difficultyRating: 4,
    },
  },

  /* ── Looks 004–010: Additional collection entries ─────────────────── */

  {
    lookId: 'look-004-ash-meridian',
    lookSlug: 'ash-meridian',
    lookTitle: 'Ash Meridian',
    season: 'AW',
    year: 2026,
    heroImageUrl: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=1400&q=90&auto=format&fit=crop',
    heroImageAlt: 'Draped ash-grey wide-sleeve coat on a rooftop in Westlands Nairobi',
    priceKES: 42000,
    availableUnits: 4,
    status: 'published',
    publishedAt: '2026-03-20T08:00:00Z',
    editorialStory: {
      lookTitle: 'Ash Meridian',
      season: 'AW',
      year: 2026,
      pullQuote: 'Ash is what remains after the argument — cool, light, absolute.',
      narrativeBody:
        'The colour named ash exists only in the moment after burning. It carries the memory of what it was without insisting on it.\n\nThis coat is cut in a wide-sleeve silhouette that references the draped robes of Northern Kenya — the kaross reinterpreted as a garment for Nairobi nights. The shoulders are extended by four centimetres beyond the natural point, creating a horizontal geometry that reads across a room before the face does.',
      moodKeywords: ['ash', 'rooftop', 'west', 'drape', 'cool'],
      credits: {
        photographer: 'Amara Osei',
        tailor: 'Wanjiku Mwangi',
        location: 'Westlands, Nairobi',
      },
    },
    tailorSpec: {
      lookId: 'look-004-ash-meridian',
      fabricComposition: [
        {
          layerName: 'Shell',
          materialName: 'Boiled Cashmere-Wool Blend',
          composition: '60% Wool, 40% Cashmere',
          weightGSM: 320,
          sourceRegion: 'Imported — Scotland',
        },
      ],
      stitchingMethod: 'Loose drape construction. No interlining. Dropped shoulder seam set 4cm beyond natural. Invisible hand-stitched hem.',
      constructionNotes: 'Single panel front. No buttons — held closed by weight and posture. Slash pockets at hip, angled 15° forward.',
      measurements: { chest: 102, shoulderWidth: 48, sleeveLength: 56 },
      tailorNotes: 'Never hang this coat — store folded. The drape structure will distort under its own weight on a hanger over time.',
      estimatedHours: 38,
      difficultyRating: 3,
    },
  },

  {
    lookId: 'look-005-copper-declension',
    lookSlug: 'copper-declension',
    lookTitle: 'Copper Declension',
    season: 'AW',
    year: 2026,
    heroImageUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1400&q=90&auto=format&fit=crop',
    heroImageAlt: 'Copper-tone structured blazer and wide-leg trouser in Ngong Hills light',
    priceKES: 61000,
    availableUnits: 2,
    status: 'published',
    publishedAt: '2026-03-22T08:00:00Z',
    editorialStory: {
      lookTitle: 'Copper Declension',
      season: 'AW',
      year: 2026,
      pullQuote: 'There are three ways to conjugate copper: raw, hammered, worn.',
      narrativeBody:
        'Copper is an activist colour. It insists on being seen. The blazer-and-trouser set refuses to apologise for this.\n\nWoven from a warp-faced twill where the copper thread runs longitudinally — never across — the fabric catches light in one direction only. The effect is directional: facing the sun, blinding; facing away, nearly brown. The garment changes with the wearer\'s movement.',
      moodKeywords: ['copper', 'activist', 'directional', 'light', 'hills'],
      credits: {
        photographer: 'Seun Adeyemi',
        tailor: 'Grace Otieno',
        model: 'Aisha Kimani',
        location: 'Ngong Hills',
      },
    },
    tailorSpec: {
      lookId: 'look-005-copper-declension',
      fabricComposition: [
        {
          layerName: 'Shell',
          materialName: 'Warp-Face Copper Twill',
          composition: '75% Wool, 25% Metallic Thread',
          weightGSM: 340,
          sourceRegion: 'Imported — Italy',
        },
        {
          layerName: 'Lining',
          materialName: 'Hammered Silk',
          composition: '100% Silk',
          weightGSM: 85,
          sourceRegion: 'Imported — China',
        },
      ],
      stitchingMethod: 'Structured bespoke construction. Full floating canvas chest piece. Hand-padstitched lapels.',
      constructionNotes: '2-button blazer, peak lapel. Wide-leg trouser — 26cm hem. Extended waistband with single hook-and-bar closure.',
      measurements: { chest: 94, waist: 80, hip: 96, shoulderWidth: 43, sleeveLength: 62 },
      tailorNotes: 'The metallic thread will snag if handled roughly — always use the press cloth when pressing. Never use a rotary cutter; straight shears only.',
      estimatedHours: 72,
      difficultyRating: 5,
    },
  },

  {
    lookId: 'look-006-salt-plain',
    lookSlug: 'salt-plain',
    lookTitle: 'Salt Plain',
    season: 'SS',
    year: 2026,
    heroImageUrl: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=1400&q=90&auto=format&fit=crop',
    heroImageAlt: 'White linen midi dress shot in harsh midday Rift Valley light',
    priceKES: 28000,
    availableUnits: 7,
    status: 'published',
    publishedAt: '2026-03-24T08:00:00Z',
    editorialStory: {
      lookTitle: 'Salt Plain',
      season: 'SS',
      year: 2026,
      pullQuote: 'The Rift Valley has no interest in flattering you — this dress has the same opinion.',
      narrativeBody:
        'Linen at noon in the Rift is brutal. It bleaches faster than memory. This dress is designed for exactly that exposure — pre-washed four times before cutting so the colour has already made its peace with the sun.\n\nThe silhouette is column, slightly A-line from the knee, with a single seam that runs on the bias from the right shoulder to the left hip. This seam is the only thing that moves in a crosswind.',
      moodKeywords: ['salt', 'noon', 'linen', 'rift', 'bleach'],
      credits: {
        photographer: 'Amara Osei',
        tailor: 'Wanjiku Mwangi',
        location: 'Lake Magadi, Rift Valley',
      },
    },
    tailorSpec: {
      lookId: 'look-006-salt-plain',
      fabricComposition: [
        {
          layerName: 'Shell',
          materialName: 'Pre-Washed Belgian Linen',
          composition: '100% Linen',
          weightGSM: 175,
          sourceRegion: 'Imported — Belgium',
        },
      ],
      stitchingMethod: 'French seams throughout. Bias-cut single side seam hand-basted before machine-stitching. Rolled hem at base.',
      constructionNotes: 'Midi length — 108cm from natural waist. Sleeveless. Shallow scoop neckline. Exposed shoulder with 1.2cm seam allowance left visible as design detail.',
      measurements: { chest: 86, waist: 70, hip: 90 },
      tailorNotes: 'Bias-cut sections must be hung for 24 hours before hemming — the fabric will drop and shift. Cutting and hemming on the same day will result in an uneven hem.',
      estimatedHours: 22,
      difficultyRating: 2,
    },
  },

  {
    lookId: 'look-007-indigo-latitude',
    lookSlug: 'indigo-latitude',
    lookTitle: 'Indigo Latitude',
    season: 'Resort',
    year: 2026,
    heroImageUrl: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=1400&q=90&auto=format&fit=crop',
    heroImageAlt: 'Deep indigo structured jacket and tapered trouser against a Mombasa doorway',
    priceKES: 51000,
    availableUnits: 3,
    status: 'published',
    publishedAt: '2026-03-26T08:00:00Z',
    editorialStory: {
      lookTitle: 'Indigo Latitude',
      season: 'Resort',
      year: 2026,
      pullQuote: 'Indigo is the colour of every ocean crossed to reach this coastline.',
      narrativeBody:
        'The Swahili Coast has been absorbing blue for a thousand years. Indigo arriving by dhow, by trade route, by insistence. This jacket holds that history in its dye — natural indigo fermented in a pot in Lamu for eleven days before the first dip.\n\nThe silhouette is an answer to the heat: structured at the shoulder, loose through the body, tapering at the cuff to a single button. It is a jacket that breathes.',
      moodKeywords: ['indigo', 'coast', 'dhow', 'breathe', 'lamu'],
      credits: {
        photographer: 'Seun Adeyemi',
        tailor: 'Grace Otieno',
        location: 'Old Town, Mombasa',
      },
    },
    tailorSpec: {
      lookId: 'look-007-indigo-latitude',
      fabricComposition: [
        {
          layerName: 'Shell',
          materialName: 'Lamu Indigo-Dyed Cotton Twill',
          composition: '100% Cotton',
          weightGSM: 260,
          sourceRegion: 'Lamu Island, Kenya',
        },
      ],
      stitchingMethod: 'Unlined for breathability. All seams finished with Hong Kong binding in matching fabric. Collar: 2-piece stand-fall.',
      constructionNotes: 'Relaxed single-breasted jacket. 2 buttons. Patch pockets at hip. No chest pocket — clean front. Back pleat for ease.',
      measurements: { chest: 98, waist: 90, shoulderWidth: 44, sleeveLength: 61 },
      tailorNotes: 'Natural indigo will transfer onto light garments when wet. Advise client to avoid wearing with light linens in the first three washes.',
      estimatedHours: 34,
      difficultyRating: 3,
    },
  },

  {
    lookId: 'look-008-ochre-stance',
    lookSlug: 'ochre-stance',
    lookTitle: 'Ochre Stance',
    season: 'AW',
    year: 2026,
    heroImageUrl: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=1400&q=90&auto=format&fit=crop',
    heroImageAlt: 'Ochre double-breasted coat photographed at golden hour in Karen',
    priceKES: 59000,
    availableUnits: 1,
    status: 'published',
    publishedAt: '2026-03-28T08:00:00Z',
    editorialStory: {
      lookTitle: 'Ochre Stance',
      season: 'AW',
      year: 2026,
      pullQuote: 'Every golden hour in Karen belongs to a coat like this.',
      narrativeBody:
        'Ochre is a Kenyan colour. Not adopted — native. It lives in the soil, in the walls of old homes, in the light at 5pm when the sun drops behind Ngong.\n\nThis double-breasted coat claims that colour without reservation. Six buttons, wide peak lapel, full back sweep. It is designed to photograph at dusk and to last forty years.',
      moodKeywords: ['ochre', 'dusk', 'karen', 'peak-lapel', 'forty-years'],
      credits: {
        photographer: 'Amara Osei',
        tailor: 'Wanjiku Mwangi',
        stylist: 'Kefilwe Nkosi',
        location: 'Karen, Nairobi',
      },
    },
    tailorSpec: {
      lookId: 'look-008-ochre-stance',
      fabricComposition: [
        {
          layerName: 'Shell',
          materialName: 'Brushed Merino Tweed',
          composition: '90% Merino Wool, 10% Alpaca',
          weightGSM: 420,
          sourceRegion: 'Imported — Ireland',
        },
        {
          layerName: 'Lining',
          materialName: 'Bemberg Cupro',
          composition: '100% Cupro',
          weightGSM: 95,
          sourceRegion: 'Imported — Japan',
        },
      ],
      stitchingMethod: 'Full-floating canvas. Hand-padstitched chest and lapels. Buttons: reclaimed buffalo horn — 6 front, 4 sleeve.',
      constructionNotes: 'Double-breasted, 6×2 button. Wide peak lapel. Full lining. Welted chest pocket. Jetted hip pockets with button. Back half-belt.',
      measurements: { chest: 100, waist: 88, hip: 102, shoulderWidth: 44, sleeveLength: 63 },
      tailorNotes: 'The alpaca content causes the fabric to felt under high heat or excessive moisture. Never steam directly — always use a dry press cloth at 150°C maximum.',
      estimatedHours: 78,
      difficultyRating: 5,
    },
  },

  {
    lookId: 'look-009-sisal-bone',
    lookSlug: 'sisal-bone',
    lookTitle: 'Sisal & Bone',
    season: 'SS',
    year: 2026,
    heroImageUrl: 'https://images.unsplash.com/photo-1544441893-675973e31985?w=1400&q=90&auto=format&fit=crop',
    heroImageAlt: 'Natural sisal-toned trouser suit on the Nairobi arboretum path',
    priceKES: 38000,
    availableUnits: 5,
    status: 'published',
    publishedAt: '2026-03-30T08:00:00Z',
    editorialStory: {
      lookTitle: 'Sisal & Bone',
      season: 'SS',
      year: 2026,
      pullQuote: 'Everything that grows in dry earth carries its own structure.',
      narrativeBody:
        'Sisal is one of Kenya\'s oldest exports. The agave fibre — extracted, spun, woven — is a material history before it is anything else. This suit references that history at the colour level: not mimicking the plant, but acknowledging it.\n\nThe trouser suit is unlined, with a single-button blazer that sits exactly on the natural waist. It reads as informal and is deeply structured.',
      moodKeywords: ['sisal', 'bone', 'arboretum', 'dry', 'structure'],
      credits: {
        photographer: 'Seun Adeyemi',
        tailor: 'Grace Otieno',
        location: 'Nairobi Arboretum',
      },
    },
    tailorSpec: {
      lookId: 'look-009-sisal-bone',
      fabricComposition: [
        {
          layerName: 'Shell',
          materialName: 'Raw Linen-Cotton Blend',
          composition: '55% Linen, 45% Cotton',
          weightGSM: 195,
          sourceRegion: 'Thika, Kenya',
        },
      ],
      stitchingMethod: 'Unlined blazer — all seams finished with 3-thread overlock. Trouser seams: flat-felled. Hems: hand-rolled.',
      constructionNotes: 'Single-button blazer, notch lapel. Straight-leg trouser, mid-rise, 24cm hem. Blazer back: single vent.',
      measurements: { chest: 90, waist: 74, hip: 92, shoulderWidth: 40, sleeveLength: 59, inseam: 76 },
      tailorNotes: 'This blend will shrink up to 3% on first wash. Pre-shrink before cutting by soaking in cold water for 2 hours, then line-drying flat.',
      estimatedHours: 31,
      difficultyRating: 3,
    },
  },

  {
    lookId: 'look-010-night-latitude',
    lookSlug: 'night-latitude',
    lookTitle: 'Night Latitude',
    season: 'Resort',
    year: 2026,
    heroImageUrl: 'https://images.unsplash.com/photo-1485462537746-965f33f8f2c0?w=1400&q=90&auto=format&fit=crop',
    heroImageAlt: 'Midnight-blue slip dress with architectural back detail photographed at night',
    priceKES: 36000,
    availableUnits: 0,
    status: 'sold-out',
    publishedAt: '2026-03-15T08:00:00Z',
    editorialStory: {
      lookTitle: 'Night Latitude',
      season: 'Resort',
      year: 2026,
      pullQuote: 'At exactly one degree south of the equator, night is a different language.',
      narrativeBody:
        'The equatorial night is not dark — it is saturated. Navy, midnight, the colour of deep ocean water. This slip dress is cut from a washed silk charmeuse that holds that depth without effort.\n\nThe architectural back detail — a single strap that crosses at the mid-spine before meeting the waist — is the only complexity. Everything else is the absence of decoration.',
      moodKeywords: ['midnight', 'equator', 'saturated', 'silk', 'crossing'],
      credits: {
        photographer: 'Amara Osei',
        tailor: 'Wanjiku Mwangi',
        model: 'Zara Muthoni',
        location: 'Nairobi',
      },
    },
    tailorSpec: {
      lookId: 'look-010-night-latitude',
      fabricComposition: [
        {
          layerName: 'Shell',
          materialName: 'Washed Silk Charmeuse',
          composition: '100% Silk',
          weightGSM: 75,
          sourceRegion: 'Imported — Japan',
        },
      ],
      stitchingMethod: 'French seams at all internal seams. Hand-rolled hem. Invisible zip at left side — 35cm.',
      constructionNotes: 'Bias-cut slip dress, midi length. Single crossing back strap. Minimal gathering at waist through bias cut only — no darts.',
      measurements: { chest: 84, waist: 68, hip: 88 },
      tailorNotes: 'Charmeuse is cut-once — no second chances. Mark with chalk only, never pins through the face. Use weights to hold pattern pieces.',
      estimatedHours: 26,
      difficultyRating: 4,
    },
  },
]
